import = ["~/.config/alacritty/themes/themes/kanagawa_wave.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

# window
[window]
opacity = 0.8
blur = true
option_as_alt = "Both"
decorations = "buttonless"
startup_mode = "Maximized"

[window.padding]
x = 10
y = 10

[window.dimensions]
lines = 40
columns = 160

[window.position]
x = 100
y = 100

# font
[font]
normal.family = "HackGen Console NF"
normal.style = "Regular"
bold.family = "HackGen Console NF"
bold.style = "Bold"
size = 12

# alacritty起動時にtmuxを一緒に起動させたい時に使う
# [shell]
# program = "/bin/zsh"
# args = ["-l", "-c", "zellij attach --index 0 --create"]
