import = ["~/.config/alacritty/themes/themes/kanagawa_wave.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dimensions.lines = 40
dimensions.columns = 160
position.x = 100
position.y = 100
opacity = 0.8
blur = true
option_as_alt = "Both"

[font]
normal.family = "HackGen Console NF"
normal.style = "Regular"
bold.family = "HackGen Console NF"
bold.style = "Bold"
size = 16
